import {
    Apple,
    Banana,
    Beef,
    Beer,
    Cake,
    Carrot,
    ChefHat,
    Cherry,
    Citrus,
    Coffee,
    Cookie,
    Croissant,
    CupSoda,
    Donut,
    Drumstick,
    Egg,
    EggFried,
    Fish,
    Flame,
    GlassWater,
    Grape,
    IceCreamBowl,
    IceCreamCone,
    Lollipop,
    Martini,
    Milk,
    Pizza,
    Popcorn,
    Salad,
    Sandwich,
    Soup,
    Sparkles,
    Sprout,
    Tag,
    Utensils,
    Wheat,
    Wine,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
    Apple,
    Banana,
    Beef,
    Beer,
    Cake,
    Carrot,
    ChefHat,
    Cherry,
    Citrus,
    Coffee,
    Cookie,
    Croissant,
    CupSoda,
    Donut,
    Drumstick,
    Egg,
    EggFried,
    Fish,
    Flame,
    GlassWater,
    Grape,
    IceCreamBowl,
    IceCreamCone,
    Lollipop,
    Martini,
    Milk,
    Pizza,
    Popcorn,
    Salad,
    Sandwich,
    Soup,
    Sparkles,
    Sprout,
    Tag,
    Utensils,
    Wheat,
    Wine,
};

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICONS);

export function getCategoryIcon(name: string | null | undefined): LucideIcon | null {
    if (!name) {
        return null;
    }

    return CATEGORY_ICONS[name] ?? null;
}